"""
SessionAuthManager — secure cookie handling for fcdownloader-extractor.

Security invariants (enforced here, never by callers):
  - Never log raw cookie values or auth headers.
  - Reject oversized cookie blobs before parsing.
  - Write temp cookie files to /tmp with mode 0o600; delete immediately after
    yt-dlp opens them (yt-dlp reads the file into memory at open time).
  - Redact in log output: show count of cookie pairs, never names or values.
"""
from __future__ import annotations

import os
import tempfile
import time
import urllib.parse

from config import COOKIE_MAX_BYTES, MOBILE_UA


# ── Validation ────────────────────────────────────────────────────────────────


class CookieTooLargeError(ValueError):
    """Raised when a cookie blob exceeds COOKIE_MAX_BYTES."""


class CookieFormatError(ValueError):
    """Raised when a cookie blob is structurally invalid (no k=v pairs)."""


def validate_cookies(cookies: str | None) -> str | None:
    """Validate and normalise a raw Cookie header string.

    Returns the stripped cookie string, or None if empty.
    Raises CookieTooLargeError or CookieFormatError on bad input.
    Never logs the cookie value.
    """
    if not cookies:
        return None
    raw = cookies.strip()
    if not raw:
        return None

    # Size guard — before any parsing
    if len(raw.encode("utf-8", errors="replace")) > COOKIE_MAX_BYTES:
        raise CookieTooLargeError(
            f"cookie payload exceeds {COOKIE_MAX_BYTES // 1024} KB limit"
        )

    # Must contain at least one name=value pair
    pairs = [p.strip() for p in raw.split(";") if p.strip()]
    valid_pairs = [p for p in pairs if "=" in p]
    if not valid_pairs:
        raise CookieFormatError("no valid name=value cookie pairs found")

    return raw


def redact_cookie_summary(cookies: str | None) -> str:
    """Return a safe log-friendly summary like '5 pairs' — never the values."""
    if not cookies:
        return "none"
    pairs = [p.strip() for p in cookies.split(";") if "=" in p.strip()]
    return f"{len(pairs)} pairs"


# ── Temp-file writer ──────────────────────────────────────────────────────────


def write_cookie_file(cookies: str, page_url: str) -> str | None:
    """Write a per-request Netscape cookies.txt file and return its path.

    The file is created with mode 0o600 (owner-read-only).  Caller MUST delete
    the file (via unlink_cookie_file) immediately after yt-dlp has opened it.

    Returns None if no valid cookies could be written.
    Raises CookieTooLargeError or CookieFormatError on invalid input.
    Never logs cookie names or values.
    """
    # Validate size and format before any disk I/O.
    validated = validate_cookies(cookies)
    if validated is None:
        return None
    cookies = validated

    # Determine the registrable domain for the cookie scope.
    host = ""
    try:
        host = (
            urllib.parse.urlparse(page_url).hostname or ""
        ).encode("idna").decode("ascii")
    except Exception:
        pass
    if not host:
        return None

    parts = host.split(".")
    reg_domain = (
        ".".join(parts[-2:])
        if len(parts) > 2 and len(parts[-1]) >= 2
        else host
    )

    # Weibo spans weibo.com + weibo.cn; mirror cookies to both.
    domain_fields: list[str]
    if reg_domain in {"weibo.com", "weibo.cn"}:
        domain_fields = [".weibo.com", ".weibo.cn"]
    else:
        domain_fields = ["." + reg_domain]

    expiry = int(time.time()) + 86400  # 24 h

    fd, path = tempfile.mkstemp(suffix="-user-cookies.txt", prefix="fcd_")
    try:
        os.chmod(path, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8", errors="replace") as tmp:
            tmp.write("# Netscape HTTP Cookie File\n")
            tmp.write("# Generated by fcdownloader-extractor per-request\n")
            for raw in cookies.split(";"):
                raw = raw.strip()
                if not raw or "=" not in raw:
                    continue
                name, _, value = raw.partition("=")
                name = _sanitise(name.strip())
                value = _sanitise(value.strip())
                if not name:
                    continue
                for domain_field in domain_fields:
                    tmp.write(
                        f"{domain_field}\tTRUE\t/\tFALSE\t{expiry}\t{name}\t{value}\n"
                    )
    except Exception:
        # Best-effort cleanup; don't leak path on error.
        try:
            os.unlink(path)
        except Exception:
            pass
        raise

    return path


def unlink_cookie_file(path: str | None) -> None:
    """Delete a temp cookie file.  Safe to call with None or a missing path."""
    if path:
        try:
            os.unlink(path)
        except Exception:
            pass


# ── Platform auth capability detection ───────────────────────────────────────


def can_supply_cookies(platform: str) -> bool:
    """Return whether *platform* can realistically supply session cookies.

    - browser_extension / android: Yes — they run in the user's browser
      context (or Android WebView with cookie access).
    - web_app: No — HttpOnly cookies are invisible to JS, so the bookmarklet
      cannot capture them.  The server's shared YT_COOKIES_BASE64 is the
      only fallback.
    - ios: Depends on WKWebView cookie access (limited).
    """
    return platform in {"browser_extension", "android", "ios"}


# ── Internal ──────────────────────────────────────────────────────────────────


def _sanitise(value: str) -> str:
    """Strip characters that are invalid in a Netscape cookie file field."""
    # Tab, newline, carriage-return break the TSV format
    return value.replace("\t", " ").replace("\n", " ").replace("\r", " ")
