# fly.toml app configuration file generated for fcdownloader-extractor on 2026-05-23T13:03:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fcdownloader-extractor'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 40
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
